steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - agent/sandbox/evaluator/Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-south1-docker.pkg.dev/exaai-sdk/sandbox-images/repo-evaluator:latest
